name: Build and Release AION Desktop Assistant

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      continue-on-error: true

    - name: Publish Windows x64
      run: |
        dotnet publish --configuration Release --runtime win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true --output ./publish/win-x64

    - name: Publish Windows x86
      run: |
        dotnet publish --configuration Release --runtime win-x86 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true --output ./publish/win-x86

    - name: Create Installation Package
      run: |
        mkdir -p ./release
        7z a -tzip ./release/AION-Desktop-Assistant-Win-x64.zip ./publish/win-x64/*
        7z a -tzip ./release/AION-Desktop-Assistant-Win-x86.zip ./publish/win-x86/*

    - name: Upload Windows x64 Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AION-Desktop-Assistant-Win-x64
        path: ./publish/win-x64/

    - name: Upload Windows x86 Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AION-Desktop-Assistant-Win-x86
        path: ./publish/win-x86/

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: AION Desktop Assistant ${{ github.ref }}
        body: |
          # 🤖 AION Desktop Assistant Release

          ## ✨ Features
          - 🎤 Voice Control with Speech Recognition
          - 👁️ Screen Reading with OCR
          - 🖱️ Mouse and Keyboard Automation
          - 🪟 Window Management
          - ♿ Accessibility-First Design

          ## 📦 Downloads
          - **Windows x64**: For 64-bit Windows 10/11
          - **Windows x86**: For 32-bit Windows systems

          ## 🛠️ Installation
          1. Download the appropriate version for your system
          2. Extract the ZIP file
          3. Run `AionDesktopAssistant.exe` as Administrator
          4. Configure microphone permissions
          5. Start using voice commands!

          ## 🎯 Voice Commands
          - "Read screen" - Read visible text
          - "Click [element]" - Click on UI elements
          - "Switch to [window]" - Change active window
          - "Type [text]" - Input text
          - "Help" - Get available commands

          ## 📋 Requirements
          - Windows 10/11
          - .NET 8.0 Runtime (included in self-contained build)
          - Microphone for voice control
          - Administrative privileges for automation

          ---
          **Empowering Independence Through Technology** 🌟
        draft: false
        prerelease: false

    - name: Upload Release Asset - Windows x64
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/AION-Desktop-Assistant-Win-x64.zip
        asset_name: AION-Desktop-Assistant-Win-x64.zip
        asset_content_type: application/zip

    - name: Upload Release Asset - Windows x86
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/AION-Desktop-Assistant-Win-x86.zip
        asset_name: AION-Desktop-Assistant-Win-x86.zip
        asset_content_type: application/zip